FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    PyYAML==6.0.2 \
    psycopg2-binary==2.9.9 \
    SQLAlchemy==2.0.36 \
    pandas==2.2.3 \
    streamlit==1.40.2 \
    streamlit-autorefresh==1.0.1

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]