FROM spark:3.5.7-scala2.12-java17-python3-ubuntu

USER root

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-pip && \
    pip3 install --no-cache-dir -r /tmp/requirements.txt && \
    rm -rf /var/lib/apt/lists/*